name: CI/CD for EmployeeAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Specify your .NET version here

      - name: Restore dependencies
        run: dotnet restore EmployeeAPI.sln

      - name: Build
        run: dotnet build EmployeeAPI.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test EmployeeAPI.Test/EmployeeAPI.Test.csproj --no-restore --verbosity normal
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }} # Optional, default is docker.io

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/employeeapi:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/employeeapi:latest
